const frasesVegeta = [
  "babaus llefiscosos",
  "baliga-balaga",
  "bocamoll",
  "bola de greix",
  "brètol",
  "burro",
  "cap de suro",
  "cap pelat",
  "colla de pallassos",
  "colla de xitxarel·los",
  "covard",
  "cucs",
  "curts de mires",
  "desgraciat",
  "esquifit",
  "estaquirot",
  "gallet",
  "gamarús",
  "grassonet",
  "idiota",
  "imbècil",
  "impertinent",
  "inútil",
  "maleducat",
  "maleït",
  "maleït mocós",
  "malparit",
  "manefles",
  "me càgum…",
  "me càsum tot!",
  "merdetes",
  "microbi",
  "misèria",
  "mitja merda",
  "mocós",
  "mocós buscabregues",
  "mocós desgraciat",
  "mocós fastigós",
  "no siguis ruc",
  "pallasso",
  "patates!",
  "patètic",
  "pelacanyes",
  "petit merdós",
  "ploramiques",
  "podrit",
  "púrria",
  "rarot",
  "sabatot",
  "sacs de cargols",
  "setciències",
  "sou tres merda seques",
  "tall rodó",
  "titelles",
  "tros d’escòria",
  "tros de ferralla",
  "tros de merda",
  "tros de quòniam",
  "tros de totxo eixelebrat",
  "ximple",
  "xitxarel·lo",
  "a veure si tens pebrots…",
  "al gran vegeta no li passareu la mà per la cara!",
  "amb la cua entre les cames",
  "aneu cap a casa a prendre un got de llet calentona, si voleu… però no em feu perdre més temps!",
  "arrossegant-se com un cuc",
  "coi de nano!",
  "em fa venir ganes de vomitar",
  "em fas fàstic",
  "eren tots una colla d’aficionats",
  "és com prendre un caramel a un nen!",
  "és el campió mundial de l’estupidesa",
  "és un desgraciat de la classe més baixa",
  "et vols escapar com un nen petit, potser…",
  "fent-te fora com un gos",
  "gos que lladra, no mossega!",
  "guarda’t les ensabonades!",
  "lluna dels pebrots",
  "m’està pujant la mosca al nas",
  "m’importa una merda",
  "me les pagareu!",
  "n’hi ha per fer-me parar boig",
  "ni pessigolles",
  "no em qüestionis, mocós!",
  "no és tan burro com sembla",
  "on coi ha anat",
  "per què t’entestes a seguir-me, que potser vols anar a explicar-ho a la teva mama",
  "quan enxampi aquell parell d’esquitxos",
  "què coi és això",
  "que ets ruc o què",
  "què fas burro!",
  "quin gallina!",
  "si conegués el seu adversari, les cames li tocarien el cul…",
  "si haguessis tingut un cervell dins d’aquest cap…",
  "si només és un napbuf",
  "tu, ruc!",
  "us en penedireu, mocosos!",
  "ves a l’infern!",
  "vols que et torni a estovar"
];

const frasesLlatines = [
  "lorem ipsum dolor sit amet",
  "consectetur adipiscing elit",
  "sed do eiusmod tempor incididunt",
  "ut labore et dolore magna aliqua",
  "ut enim ad minim veniam",
  "quis nostrud exercitation ullamco",
  "duis aute irure dolor in reprehenderit",
  "excepteur sint occaecat cupidatat",
  "non proident sunt in culpa",
  "qui officia deserunt mollit",
  "nulla pariatur excepteur sint",
  "sunt in culpa qui officia",
  "deserunt mollit anim id est",
  "in voluptate velit esse cillum",
  "dolore eu fugiat nulla pariatur",
  "laboris nisi ut aliquip ex ea",
  "commodo consequat suis aute",
  "irure dolor in reprehenderit",
  "velit esse cillum dolore eu",
  "fugiat nulla pariatur excepteur",
  "sint occaecat cupidatat non",
  "proident sunt in culpa qui",
  "officia deserunt mollit anim",
  "id est laborum et dolorum",
  "tempor incididunt ut labore",
  "et dolore magna aliqua enim",
  "veniam quis nostrud exercitation",
  "ullamco laboris nisi ut aliquip",
  "ex ea commodo consequat duis",
  "aute irure dolor in reprehen"
];